name: Deploy to Solana (Docker)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Anchor in Docker
        env:
          SOLANA_WALLET: ${{ secrets.SOLANA_WALLET }}
        run: |
          echo "$SOLANA_WALLET" > wallet.json

          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            -e ANCHOR_WALLET=/project/wallet.json \
            -e SOLANA_URL=https://api.devnet.solana.com \
            coralxyz/anchor:latest \
            bash -c "anchor build && solana program deploy target/deploy/simple_counter.so --url devnet"
